import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Chitramela 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="main-layout">
        {children}
      </body>
    </html>
  );
}
